root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/splitter ./cmd/splitter"
  bin = "tmp/splitter"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "vendor"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  full_bin = ""
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  delay = 0
  stop_on_error = true
  rerun = false
  rerun_delay = 500

[color]
  main = "lightblue"
  watcher = "green"
  build = "yellow"
  runner = "magenta"

[log]
  time = true
  main_only = false
